# Generated by Django 4.1.2 on 2022-10-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Post',
        ),
    ]
